version: '3.3'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    # ports:
    #   - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  api:
    depends_on:
      - db
    build: .
    restart: unless-stopped
    environment:
      - PORT=5050
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres?sslmode=disable
      - ENDPOINT=127.0.0.1
      - ENDPORT=5001
    # ports:
    #   - '5050:5050'
    extra_hosts:
      - "host.docker.internal:127.0.0.1"
    logging:
      options:
        max-size: "2m"
        max-file: "3"
    # stdin_open: true
    # tty: true
    stdin_open: true
    tty: true
volumes:
  db:
    driver: local