version: '3.3'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    network_mode: "host"
    # ports:
    #   - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  api:
    depends_on:
      - db
    build: .
    restart: unless-stopped
    environment:
      - PORT=${API_PORT}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@127.0.0.1:5432/postgres?sslmode=disable
      - ENDPOINT=localhost
      - ENDPORT=5001
    network_mode: "host"
    # ports:
    #   - '5050:5050'
    logging:
      options:
        max-size: "2m"
        max-file: "3"
    # stdin_open: true
    # tty: true
    stdin_open: true
    tty: true
volumes:
  db:
    driver: local